//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPlannerWebApplication.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyPlannerEntities : DbContext
    {
        public StudyPlannerEntities()
            : base("name=StudyPlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Module_Hours> Module_Hours { get; set; }
        public virtual DbSet<Semester_Details> Semester_Details { get; set; }
        public virtual DbSet<Track_Module> Track_Module { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
